import { FormEvent, useState } from 'react';

const loads=['Есть существенный свободный ресурс','Есть небольшой резерв','Нормальная загрузка','Высокая загрузка','Критическая загрузка'];
const specialists=['Frontend','Backend','Fullstack','QA','DevOps','Аналитики','ML / AI'];
const delays=['Frontend','Backend','Согласование API','Архитектура','Аналитика / требования','QA','DevOps / CI/CD','Инфраструктура','Code Review','Релизы'];
const comps=['Vue / Angular','Backend','Системная архитектура','Аналитика','DevOps','Автоматизация тестирования','ML / AI','AI-инструменты в SDLC'];
const effects=['Сокращение time-to-market','Снижение зависимости от других команд','Сокращение количества дефектов','Более быстрые релизы','Сокращение ручной работы','Улучшение требований','Возможность делать end-to-end задачи одним разработчиком','Возможность внедрения AI-функционала'];

type S={ [k:string]: string|string[]|Record<string,number> };
const init:S={projectName:'',respondent:'',teamSize:'',stack:'',specialists:[],specialistsOther:'',frontendLoad:'',otherLoad:'',timeTasks:'',delays:[],delaysOther:'',pains:'',waiting:'',independent:'',needs:{},topCompetencies:'',effects:[],effectsOther:'',backlog:'',directions:'',examples:'',mentor:'',risks:''};

export default function App(){
 const [s,setS]=useState<S>(init),[out,setOut]=useState(''),[err,setErr]=useState(false);
 const val=(k:string)=>s[k] as string; const arr=(k:string)=>s[k] as string[];
 const set=(k:string,v:S[string])=>setS(x=>({...x,[k]:v}));
 const toggle=(k:string,v:string)=>set(k,arr(k).includes(v)?arr(k).filter(x=>x!==v):[...arr(k),v]);
 const Text=({n,label,k}:{n:string,label:string,k:string})=><label className="question"><b>{n}. {label}</b><textarea value={val(k)} onChange={e=>set(k,e.target.value)}/></label>;
 const Radio=({n,label,k,opts}:{n:string,label:string,k:string,opts:string[]})=><div className="question"><b>{n}. {label}</b>{opts.map(o=><label className="option" key={o}><input type="radio" name={k} checked={val(k)===o} onChange={()=>set(k,o)}/>{o}</label>)}</div>;
 const submit=(e:FormEvent)=>{e.preventDefault(); const req=['projectName','respondent','teamSize','stack','frontendLoad','otherLoad','timeTasks','pains','waiting','independent','topCompetencies','backlog','directions','examples','mentor','risks']; const ok=req.every(k=>val(k).trim())&&arr('specialists').length&&arr('delays').length&&arr('effects').length&&Object.keys(s.needs as object).length===comps.length; if(!ok){setErr(true);scrollTo({top:0,behavior:'smooth'});return} setErr(false); setOut(JSON.stringify({questionnaireId:'teamlead-project-needs-v1',questionnaireVersion:1,completedAt:new Date().toISOString(),answers:s},null,2));};
 return <main><header><div className="eyebrow">АНКЕТА 2</div><h1>Тимлид: состояние проекта и потребности</h1><p>Цель: понять, где проект теряет время, каких компетенций не хватает, какие навыки дадут измеримый эффект и есть ли реальные задачи для практики участников.</p></header>{err&&<div className="error">Заполните все обязательные вопросы.</div>}<form onSubmit={submit}>
 <section><h2>Блок 1. Проект</h2><Text n="1" label="Название проекта / продукта" k="projectName"/><Text n="2" label="Кто заполняет анкету" k="respondent"/><Text n="3" label="Размер команды разработки" k="teamSize"/><Text n="4" label="Основной технологический стек" k="stack"/><div className="question"><b>5. Какие специалисты сейчас есть в команде?</b>{specialists.map(o=><label className="option" key={o}><input type="checkbox" checked={arr('specialists').includes(o)} onChange={()=>toggle('specialists',o)}/>{o}</label>)}<input placeholder="Другие" value={val('specialistsOther')} onChange={e=>set('specialistsOther',e.target.value)}/></div></section>
 <section><h2>Блок 2. Текущее состояние</h2><Radio n="7" label="Насколько фронтенд-команда сейчас загружена?" k="frontendLoad" opts={loads}/><Radio n="7" label="Насколько загружены остальные члены команды?" k="otherLoad" opts={loads}/><Text n="8" label="Какие типы задач сейчас занимают непропорционально много времени?" k="timeTasks"/><div className="question"><b>9. Где чаще всего возникают задержки?</b>{delays.map(o=><label className="option" key={o}><input type="checkbox" checked={arr('delays').includes(o)} onChange={()=>toggle('delays',o)}/>{o}</label>)}<input placeholder="Другое" value={val('delaysOther')} onChange={e=>set('delaysOther',e.target.value)}/></div><Text n="10" label="Назовите три основные технические или процессные боли проекта." k="pains"/><Text n="11" label="Есть ли задачи, которые регулярно ждут специалиста из другой команды/функции? Какие?" k="waiting"/><Text n="12" label="Есть ли задачи, которые разработчики могли бы выполнять самостоятельно при наличии дополнительных компетенций? Какие?" k="independent"/></section>
 <section><h2>Блок 3. Дефицит компетенций</h2><div className="question"><b>13. Насколько проекту нужны дополнительные компетенции внутри команды?</b><p>0 — не требуется; 1 — полезно; 2 — желательно; 3 — существенно; 4 — критично.</p>{comps.map(c=><div className="rating" key={c}><span>{c}</span>{[0,1,2,3,4].map(n=><label key={n}><input type="radio" name={c} checked={(s.needs as Record<string,number>)[c]===n} onChange={()=>set('needs',{...(s.needs as Record<string,number>),[c]:n})}/>{n}</label>)}</div>)}</div><Text n="14" label="Какие три компетенции дали бы проекту наибольший эффект?" k="topCompetencies"/><div className="question"><b>15. Какой эффект ожидается?</b>{effects.map(o=><label className="option" key={o}><input type="checkbox" checked={arr('effects').includes(o)} onChange={()=>toggle('effects',o)}/>{o}</label>)}<input placeholder="Другое" value={val('effectsOther')} onChange={e=>set('effectsOther',e.target.value)}/></div></section>
 <section><h2>Блок 4. Практика для участников обучения</h2><Radio n="20" label="Есть ли в бэклоге реальные задачи, которые можно дать разработчикам для получения опыта в смежной области?" k="backlog" opts={['Да','Скорее да','Пока нет']}/><Text n="21" label="По каким направлениям такие задачи есть?" k="directions"/><Text n="22" label="Приведите 2–5 примеров подходящих задач из бэклога." k="examples"/><Radio n="23" label="Есть ли на проекте люди, которые могут быть ментором/ревьюером?" k="mentor" opts={['Да','Возможно','Нет']}/><Text n="24" label="Какие ограничения или риски вы видите?" k="risks"/></section><button className="submit" type="submit">Результат</button></form>{out&&<section><div className="resultHead"><h2>Результат JSON</h2><button onClick={()=>navigator.clipboard.writeText(out)}>Скопировать JSON</button></div><pre>{out}</pre></section>}</main>;
}
